
shell zsh
font_size 16

font_family      family="SauceCodePro Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

# defaults
scrollback_lines 10000
copy_on_select no
strip_trailing_spaces smart
update_check_interval 0

# Terminal URL linking
# This controls behavior of links using OSC8 codes
allow_hyperlinks ask
# Visually show URLs?
detect_urls yes
# Remap click to require mod
mouse_map left click ungrabbed no-op
mouse_map kitty_mod+left click ungrabbed mouse_handle_click link

# fix scroll
touch_scroll_multiplier 5
wheel_scroll_multiplier 5

# remap shortcuts
# remember CWD
map kitty_mod+ENTER launch --cwd=current
# move cursor between windows
map kitty_mod+. move_window_forward
map kitty_mod+, move_window_backward
map kitty_mod+LEFT previous_window
map kitty_mod+RIGHT next_window
map kitty_mod+TAB next_tab
map kitty_mod+TAB previous_tab

# tab detaching
map kitty_mod+f3 detach_window new-tab
map kitty_mod+f4 detach_window ask

map kitty_mod+f6 detach_tab
map kitty_mod+f7 detach_tab ask

map kitty_mod+f8 goto_session ~/.config/kitty/sessions

# remoting
allow_remote_control yes

# performance ~ 10fps
repaint_delay 100
input_delay 10

# default size
startup_session default
tab_title_template "{index}: {title}"
remember_window_size  no
initial_window_width  960
initial_window_height 600
enabled_layouts vertical, tall, fat, horizontal

# theming
dynamic_background_opacity true
background_opacity 0.88
background_tint 0.5
wayland_titlebar_color background

# vim:fileencoding=utf-8:ft=conf
