{{- if eq .dev_machine true }}
tenv:
  type: archive
  url: {{ gitHubReleaseAssetURL "tofuutils/tenv" "v4.14.8" "tenv_*_Linux_x86_64.tar.gz" }}
  targetPath: .local/bin/
  checksum:
    sha256: "7a1774a9422d2713ee2991fff17e615077f340993a086d8ef2c590982950f6b8"
  include:
    - tenv
    - tf
    - terraform
tf-docs:
  type: archive-file
  url: {{ gitHubReleaseAssetURL "terraform-docs/terraform-docs" "v0.24.0" "terraform-docs-*-linux-amd64.tar.gz" }}
  path: terraform-docs
  targetPath: .local/bin/terraform-docs
  checksum:
    sha256: "9005daf969de0b50134493a2c00078b49f5f5b39d021cda7c89bf4d4f3d776d3"
terraform-ls:
  type: archive-file
  url: https://releases.hashicorp.com/terraform-ls/0.38.8/terraform-ls_0.38.8_linux_amd64.zip
  path: terraform-ls
  targetPath: .local/bin/terraform-ls
  checksum:
    sha256: "d16077d9c83f13ac33501af49ea75f43218d3fa2437c6c1374550b2625edc3ef"
{{- end }}
